expr = term , [ ( "+" | "-" ) , epxr ] ;
term = indexed value , [ ( "*" | "/" ) , term ] ;
indexed value = value , ( [ "^" , index ] , [ "_" , index ] ) | ( [ "_" , index ] , [ "^" , index ] ) ;
index = raw value | group ;
group = "{" , expr , "}" ;
value = [ "+" | "-" ] , ( raw value | group | bracket expr | fraction | binomial | root ) ;
raw value = ? number ? | ? letter ? | ? greek letter ? ;
bracket expr = "{" , expr , "}" | "(" , expr , ")" | "[" , expr , "]" | "\{" , expr , "\}" ;
fraction = "\frac" , group , group ;
binomial = "\binom" , group , group ;
root = "\sqrt" , [ argument ] , group ;
argument = "[" , expression , "]" ;
